name: progress_state_button_example
description: A customizable progress button for Flutter.
version: 1.0.1
authors: [
  Selim YILDIZ <slmyldz41@gmail.com>,
]
homepage: https://github.com/slm/progress-state-button
issue_tracker: https://github.com/slm/progress-state-button/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  progress_state_button:
      path: ../

flutter:
  uses-material-design: true